#ifndef FBC_THIRD_PARTY_LIBRARY_TEST_MSHADOW_TEST_HPP_
#define FBC_THIRD_PARTY_LIBRARY_TEST_MSHADOW_TEST_HPP_

int test_mshadow_1();
int test_mshadow_2();

#endif // FBC_THIRD_PARTY_LIBRARY_TEST_MSHADOW_TEST_HPP_

